version: '3.0'

services:
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - 9000:9000
  
  ecommerce:
    build: .
    container_name: ecommerce-checkout
    ports:
      - 8181:8080
    links:
      - sonarqube


